# Generated by Django 5.2.4 on 2025-07-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_topiccategory_remove_lesson_subject_randomtopic'),
        ('quizzes', '0002_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_d',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points_value',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='quiz_images/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.randomtopic'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
